#!/usr/bin/env python3
"""Regenerate src/native/device/dreamcast/vmu_default_icondata.h from a
1024-byte ICONDATA.VMS file. The virtual VMU drops this file in at
preformat so a freshly-initialized memory card already shows a logo in
the Dreamcast BIOS instead of the no-icon placeholder.

Usage:
    python3 tools/vmu/gen_default_icondata.py <path/to/ICONDATA.VMS>

VMS layout (sanity-checked, not enforced):
    0x000..0x00F  16-byte description shown by DC BIOS
    0x010..0x01F  16-byte secondary description / app id
    0x020..0x09F  32x32 1-bit mono icon (128 bytes)
    0x0A0..0x0BF  16-entry color palette (16-bit LE RGB, 32 bytes)
    0x0C0..0x2BF  32x32 4-bit color icon (512 bytes)
    0x2C0..0x3FF  reserved padding to 1024
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT  = ROOT / "src/native/device/dreamcast/vmu_default_icondata.h"


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <ICONDATA.VMS>")
    src = Path(sys.argv[1])
    data = src.read_bytes()
    if len(data) != 1024:
        sys.exit(f"error: ICONDATA.VMS must be exactly 1024 bytes (got {len(data)})")

    lines = [
        "// Auto-generated by tools/vmu/gen_default_icondata.py.",
        "// Joypad OS default VMU icon: shown by the Dreamcast BIOS when the freshly",
        "// initialized virtual memory card is browsed in the system menu. Written",
        "// into save-area blocks 0-1 by vmu_preformat() and pointed at by a single",
        "// directory entry named 'ICONDATA_VMS'.",
        f"// Source: {src.name}",
        "",
        "#ifndef JOYPAD_VMU_DEFAULT_ICONDATA_H",
        "#define JOYPAD_VMU_DEFAULT_ICONDATA_H",
        "",
        "#include <stdint.h>",
        "",
        "#define VMU_DEFAULT_ICONDATA_SIZE 1024u",
        "",
        "static const uint8_t vmu_default_icondata[VMU_DEFAULT_ICONDATA_SIZE] = {",
    ]
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i+16])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append("#endif  // JOYPAD_VMU_DEFAULT_ICONDATA_H")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} (1024 bytes)")


if __name__ == "__main__":
    main()
